### PR TITLE
Allow arp to process uppercase MAC Addresses.

### PR DESCRIPTION
**Pull request by halkeye**
My router is returning:

```? (192.168.1.142) at 00:18:DD:04:E2:FA [ether]  on br0```

Added a bunch of tests to confirm letters are working properly. I tried to base it on my own router, but its in ap mode, so I can't check what the leases file looks like

### CODE REVIEW

**Comment by halkeye** [comment]
(all the other PRs were in prep for this one, so it should get quiet again after this)

**Comment by maweki** [comment]
You're allowed to use trailing commas in python lists. If this is done consistently, adding to a list is just one insertion in git instead of two insertions and one removal

**Comment by kennedyshead** [comment]
@maweki You are welcome with PR ;)

**Comment by halkeye** [comment]
> You're allowed to use trailing commas in python lists. If this is done consistently, adding to a list is just one insertion in git instead of two insertions and one removal

oh interesting. Good call. My personal style is to do not do that, because it broke in old javascript for ie11, but thats something I should start doing in python and javascript as it helps longer term.

**Comment by kennedyshead** [comment]
https://github.com/home-assistant/home-assistant/pull/18042

**Pull request merged**
