### PR TITLE
Added option to specify interface and dnsmasq location

### PR DESCRIPTION
**Pull request by pkishino**
removed hardcoded dnsmasq path and interface for statistics, helps address #26

### CODE REVIEW

**Comment by pkishino** [comment]
Can this please be merged and release created so HA can be updated?

**Comment by kennedyshead** [comment]
Nicely done 🐬 Thank you!

**Comment by pkishino** [comment]
Could you also make a new release perhaps with this included? Then it can be added to next HA release, already prepared all the content

**Comment by kennedyshead** [comment]
Done . :+1: https://pypi.org/project/aioasuswrt/1.2.0/

**Comment by kennedyshead** [comment]
Use 1.2.1 though

**Pull request merged**
